[package]
name = "wifi_password_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_WiFi",
    "Data_Xml_Dom",
] }

[[bin]]
name = "wifi_password_scanner"
path = "main.rs"
